// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBotChat = "bot-chats"

// BotChat mapped from table <bot-chats>
type BotChat struct {
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status    int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	ChatID    string    `gorm:"column:chat_id;not null" json:"chat_id"`
}

// TableName BotChat's table name
func (*BotChat) TableName() string {
	return TableNameBotChat
}
