// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCampaignDuration = "campaign-durations"

// CampaignDuration mapped from table <campaign-durations>
type CampaignDuration struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StartAt   time.Time `gorm:"column:start_at;not null;default:CURRENT_TIMESTAMP(6)" json:"start_at"`
	EndAt     time.Time `gorm:"column:end_at;not null;default:CURRENT_TIMESTAMP(6)" json:"end_at"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName CampaignDuration's table name
func (*CampaignDuration) TableName() string {
	return TableNameCampaignDuration
}
