// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCampaignReferralHistory = "campaign-referral-history"

// CampaignReferralHistory mapped from table <campaign-referral-history>
type CampaignReferralHistory struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID int32     `gorm:"column:customer_id;not null" json:"customer_id"`
	OldRank    int32     `gorm:"column:old_rank;not null" json:"old_rank"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName CampaignReferralHistory's table name
func (*CampaignReferralHistory) TableName() string {
	return TableNameCampaignReferralHistory
}
