// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCassoTransaction = "casso-transactions"

// CassoTransaction mapped from table <casso-transactions>
type CassoTransaction struct {
	ID                    int32     `gorm:"column:id;primaryKey" json:"id"`
	Tid                   string    `gorm:"column:tid" json:"tid"`
	Description           string    `gorm:"column:description" json:"description"`
	Amount                int32     `gorm:"column:amount" json:"amount"`
	CusumBalance          int32     `gorm:"column:cusum_balance" json:"cusum_balance"`
	When                  time.Time `gorm:"column:when" json:"when"`
	BankSubAccID          string    `gorm:"column:bank_sub_acc_id" json:"bank_sub_acc_id"`
	SubAccID              string    `gorm:"column:subAccId" json:"subAccId"`
	BankName              string    `gorm:"column:bankName" json:"bankName"`
	BankAbbreviation      string    `gorm:"column:bankAbbreviation" json:"bankAbbreviation"`
	VirtualAccount        string    `gorm:"column:virtualAccount" json:"virtualAccount"`
	VirtualAccountName    string    `gorm:"column:virtualAccountName" json:"virtualAccountName"`
	CorresponsiveName     string    `gorm:"column:corresponsiveName" json:"corresponsiveName"`
	CorresponsiveAccount  string    `gorm:"column:corresponsiveAccount" json:"corresponsiveAccount"`
	CorresponsiveBankID   string    `gorm:"column:corresponsiveBankId" json:"corresponsiveBankId"`
	CorresponsiveBankName string    `gorm:"column:corresponsiveBankName" json:"corresponsiveBankName"`
}

// TableName CassoTransaction's table name
func (*CassoTransaction) TableName() string {
	return TableNameCassoTransaction
}
