// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContact = "contacts"

// Contact mapped from table <contacts>
type Contact struct {
	CustomersId1 int32 `gorm:"column:customersId_1;primaryKey" json:"customersId_1"`
	CustomersId2 int32 `gorm:"column:customersId_2;primaryKey" json:"customersId_2"`
}

// TableName Contact's table name
func (*Contact) TableName() string {
	return TableNameContact
}
