// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountryLanguage = "country-language"

// CountryLanguage mapped from table <country-language>
type CountryLanguage struct {
	LanguageID string `gorm:"column:language_id;primaryKey" json:"language_id"`
	CountryID  string `gorm:"column:country_id;primaryKey" json:"country_id"`
}

// TableName CountryLanguage's table name
func (*CountryLanguage) TableName() string {
	return TableNameCountryLanguage
}
