// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountryCurrency = "country-currency"

// CountryCurrency mapped from table <country-currency>
type CountryCurrency struct {
	CurrencySymbol string `gorm:"column:currency_symbol;primaryKey" json:"currency_symbol"`
	CountryID      string `gorm:"column:country_id;primaryKey" json:"country_id"`
}

// TableName CountryCurrency's table name
func (*CountryCurrency) TableName() string {
	return TableNameCountryCurrency
}
