// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountryCallingCode = "country-calling-code"

// CountryCallingCode mapped from table <country-calling-code>
type CountryCallingCode struct {
	CallingCodeID string `gorm:"column:calling_code_id;primaryKey" json:"calling_code_id"`
	CountryID     string `gorm:"column:country_id;primaryKey" json:"country_id"`
}

// TableName CountryCallingCode's table name
func (*CountryCallingCode) TableName() string {
	return TableNameCountryCallingCode
}
