// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountryTransferMethod = "country-transfer-method"

// CountryTransferMethod mapped from table <country-transfer-method>
type CountryTransferMethod struct {
	TransferMethodID string `gorm:"column:transfer_method_id;primaryKey" json:"transfer_method_id"`
	CountryID        string `gorm:"column:country_id;primaryKey" json:"country_id"`
}

// TableName CountryTransferMethod's table name
func (*CountryTransferMethod) TableName() string {
	return TableNameCountryTransferMethod
}
