// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCurrencyProvider = "currency-provider"

// CurrencyProvider mapped from table <currency-provider>
type CurrencyProvider struct {
	CurrencySymbol string `gorm:"column:currency_symbol;primaryKey" json:"currency_symbol"`
	ProviderValue  string `gorm:"column:provider_value;primaryKey" json:"provider_value"`
}

// TableName CurrencyProvider's table name
func (*CurrencyProvider) TableName() string {
	return TableNameCurrencyProvider
}
