// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCurrencyTransferMethod = "currency-transfer-method"

// CurrencyTransferMethod mapped from table <currency-transfer-method>
type CurrencyTransferMethod struct {
	TransferMethodID string `gorm:"column:transfer_method_id;primaryKey" json:"transfer_method_id"`
	CurrencySymbol   string `gorm:"column:currency_symbol;primaryKey" json:"currency_symbol"`
}

// TableName CurrencyTransferMethod's table name
func (*CurrencyTransferMethod) TableName() string {
	return TableNameCurrencyTransferMethod
}
