// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFeeCustomer = "fee-customer"

// FeeCustomer mapped from table <fee-customer>
type FeeCustomer struct {
	FeeID      string `gorm:"column:fee_id;primaryKey" json:"fee_id"`
	CustomerID int32  `gorm:"column:customer_id;primaryKey" json:"customer_id"`
}

// TableName FeeCustomer's table name
func (*FeeCustomer) TableName() string {
	return TableNameFeeCustomer
}
