// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameField = "fields"

// Field mapped from table <fields>
type Field struct {
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status        int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted     int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	Name          string    `gorm:"column:name" json:"name"`
	Property      string    `gorm:"column:property" json:"property"`
	FieldType     string    `gorm:"column:field_type;not null;default:TEXT" json:"field_type"`
	IsRequired    int32     `gorm:"column:is_required;not null;default:1" json:"is_required"`
	RequestType   string    `gorm:"column:request_type;not null;default:KYC_LEVEL_1" json:"request_type"`
	OrdinalNumber int32     `gorm:"column:ordinal_number;not null" json:"ordinal_number"`
}

// TableName Field's table name
func (*Field) TableName() string {
	return TableNameField
}
