// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGeneralSetting = "general-settings"

// GeneralSetting mapped from table <general-settings>
type GeneralSetting struct {
	CreatedAt               time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt               time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status                  int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted               int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID                      string    `gorm:"column:id;primaryKey" json:"id"`
	SiteName                string    `gorm:"column:site_name" json:"site_name"`
	CurText                 string    `gorm:"column:cur_text" json:"cur_text"`
	CurSym                  string    `gorm:"column:cur_sym" json:"cur_sym"`
	EmailFrom               string    `gorm:"column:email_from" json:"email_from"`
	EmailTemplate           string    `gorm:"column:email_template" json:"email_template"`
	SmsBody                 string    `gorm:"column:sms_body" json:"sms_body"`
	SmsFrom                 string    `gorm:"column:sms_from" json:"sms_from"`
	BaseColor               string    `gorm:"column:base_color" json:"base_color"`
	SecondaryColor          string    `gorm:"column:secondary_color" json:"secondary_color"`
	MailConfig              string    `gorm:"column:mail_config" json:"mail_config"`
	SmsConfig               string    `gorm:"column:sms_config" json:"sms_config"`
	GlobalShortCodes        string    `gorm:"column:global_short_codes" json:"global_short_codes"`
	Kv                      int32     `gorm:"column:kv;not null" json:"kv"`
	Ev                      int32     `gorm:"column:ev;not null" json:"ev"`
	En                      int32     `gorm:"column:en;not null" json:"en"`
	Sv                      int32     `gorm:"column:sv;not null" json:"sv"`
	Sn                      int32     `gorm:"column:sn;not null" json:"sn"`
	Pn                      int32     `gorm:"column:pn;not null" json:"pn"`
	PushConfig              string    `gorm:"column:push_config;not null" json:"push_config"`
	ForceSsl                int32     `gorm:"column:force_ssl;not null" json:"force_ssl"`
	MaintenanceMode         int32     `gorm:"column:maintenance_mode;not null" json:"maintenance_mode"`
	SecurePassword          int32     `gorm:"column:secure_password;not null" json:"secure_password"`
	Agree                   int32     `gorm:"column:agree;not null" json:"agree"`
	Registration            int32     `gorm:"column:registration;not null" json:"registration"`
	ActiveTemplate          string    `gorm:"column:active_template" json:"active_template"`
	SystemInfo              string    `gorm:"column:system_info" json:"system_info"`
	Modules                 string    `gorm:"column:modules" json:"modules"`
	AccountNoLength         int32     `gorm:"column:account_no_length;not null" json:"account_no_length"`
	AccountNoPrefix         string    `gorm:"column:account_no_prefix" json:"account_no_prefix"`
	OtpTime                 int32     `gorm:"column:otp_time;not null" json:"otp_time"`
	DailyTransferLimit      int32     `gorm:"column:daily_transfer_limit;not null" json:"daily_transfer_limit"`
	MonthlyTransferLimit    int32     `gorm:"column:monthly_transfer_limit;not null" json:"monthly_transfer_limit"`
	MinimumTransferLimit    int32     `gorm:"column:minimum_transfer_limit;not null" json:"minimum_transfer_limit"`
	FixedTransferCharge     int32     `gorm:"column:fixed_transfer_charge;not null" json:"fixed_transfer_charge"`
	PercentTransferCharge   int32     `gorm:"column:percent_transfer_charge;not null" json:"percent_transfer_charge"`
	ReferralCommissionCount int32     `gorm:"column:referral_commission_count;not null" json:"referral_commission_count"`
	LastDfsCron             time.Time `gorm:"column:last_dfs_cron" json:"last_dfs_cron"`
	LastFdrCron             time.Time `gorm:"column:last_fdr_cron" json:"last_fdr_cron"`
	LastLoanCron            time.Time `gorm:"column:last_loan_cron" json:"last_loan_cron"`
	GeneralSettingStatus    string    `gorm:"column:general_setting_status;not null;default:0" json:"general_setting_status"`
}

// TableName GeneralSetting's table name
func (*GeneralSetting) TableName() string {
	return TableNameGeneralSetting
}
