// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInvoice = "invoices"

// Invoice mapped from table <invoices>
type Invoice struct {
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status      int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted   int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Name        string    `gorm:"column:name" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	CustomerID  int32     `gorm:"column:customer_id" json:"customer_id"`
	FileID      string    `gorm:"column:file_id" json:"file_id"`
}

// TableName Invoice's table name
func (*Invoice) TableName() string {
	return TableNameInvoice
}
