// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKybLevel2Data = "kyb-level2-data"

// KybLevel2Data mapped from table <kyb-level2-data>
type KybLevel2Data struct {
	CreatedAt                 time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt                 time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status                    int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted                 int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID                        string    `gorm:"column:id;primaryKey" json:"id"`
	IDNumber                  string    `gorm:"column:id_number" json:"id_number"`
	KyVerificationStatus      string    `gorm:"column:ky_verification_status;not null;default:PENDING" json:"ky_verification_status"`
	Reason                    string    `gorm:"column:reason" json:"reason"`
	Version                   int32     `gorm:"column:version;not null" json:"version"`
	CustomerID                int32     `gorm:"column:customer_id" json:"customer_id"`
	CountryID                 string    `gorm:"column:country_id" json:"country_id"`
	RegistrationCertificateID string    `gorm:"column:registration_certificate_id" json:"registration_certificate_id"`
}

// TableName KybLevel2Data's table name
func (*KybLevel2Data) TableName() string {
	return TableNameKybLevel2Data
}
