// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKycLevel2Data = "kyc-level2-data"

// KycLevel2Data mapped from table <kyc-level2-data>
type KycLevel2Data struct {
	CreatedAt              time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status                 int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted              int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID                     string    `gorm:"column:id;primaryKey" json:"id"`
	IDNumber               string    `gorm:"column:id_number" json:"id_number"`
	FullName               string    `gorm:"column:full_name" json:"full_name"`
	DateOfBirth            time.Time `gorm:"column:date_of_birth" json:"date_of_birth"`
	IdentificationType     string    `gorm:"column:identification_type;not null" json:"identification_type"`
	KyVerificationStatus   string    `gorm:"column:ky_verification_status;not null;default:PENDING" json:"ky_verification_status"`
	Reason                 string    `gorm:"column:reason" json:"reason"`
	Version                int32     `gorm:"column:version;not null" json:"version"`
	CustomerID             int32     `gorm:"column:customer_id" json:"customer_id"`
	CountryID              string    `gorm:"column:country_id" json:"country_id"`
	FontIdentificationID   string    `gorm:"column:font_identification_id" json:"font_identification_id"`
	BackIdentificationID   string    `gorm:"column:back_identification_id" json:"back_identification_id"`
	SelfieIdentificationID string    `gorm:"column:selfie_identification_id" json:"selfie_identification_id"`
}

// TableName KycLevel2Data's table name
func (*KycLevel2Data) TableName() string {
	return TableNameKycLevel2Data
}
