// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKycLevel3Data = "kyc-level3-data"

// KycLevel3Data mapped from table <kyc-level3-data>
type KycLevel3Data struct {
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status               int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted            int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID                   string    `gorm:"column:id;primaryKey" json:"id"`
	Address              string    `gorm:"column:address" json:"address"`
	DocumentType         string    `gorm:"column:document_type;not null" json:"document_type"`
	KyVerificationStatus string    `gorm:"column:ky_verification_status;not null;default:PENDING" json:"ky_verification_status"`
	Reason               string    `gorm:"column:reason" json:"reason"`
	Version              int32     `gorm:"column:version;not null" json:"version"`
	CustomerID           int32     `gorm:"column:customer_id" json:"customer_id"`
	DocumentID           string    `gorm:"column:document_id" json:"document_id"`
}

// TableName KycLevel3Data's table name
func (*KycLevel3Data) TableName() string {
	return TableNameKycLevel3Data
}
