// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKycLevel1Data = "kyc-level1-data"

// KycLevel1Data mapped from table <kyc-level1-data>
type KycLevel1Data struct {
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status               int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted            int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID                   string    `gorm:"column:id;primaryKey" json:"id"`
	Email                string    `gorm:"column:email" json:"email"`
	PhoneNumber          string    `gorm:"column:phone_number" json:"phone_number"`
	KyVerificationStatus string    `gorm:"column:ky_verification_status;not null;default:PENDING" json:"ky_verification_status"`
	Reason               string    `gorm:"column:reason" json:"reason"`
	Version              int32     `gorm:"column:version;not null" json:"version"`
	CustomerID           int32     `gorm:"column:customer_id" json:"customer_id"`
	CallingCodeID        string    `gorm:"column:calling_code_id" json:"calling_code_id"`
}

// TableName KycLevel1Data's table name
func (*KycLevel1Data) TableName() string {
	return TableNameKycLevel1Data
}
