// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLimitCustomer = "limit-customer"

// LimitCustomer mapped from table <limit-customer>
type LimitCustomer struct {
	LimitID    string `gorm:"column:limit_id;primaryKey" json:"limit_id"`
	CustomerID int32  `gorm:"column:customer_id;primaryKey" json:"customer_id"`
}

// TableName LimitCustomer's table name
func (*LimitCustomer) TableName() string {
	return TableNameLimitCustomer
}
