// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLimit = "limits"

// Limit mapped from table <limits>
type Limit struct {
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status            bool      `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted         bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	AccountType       string    `gorm:"column:account_type" json:"account_type"`
	AccountLevel      string    `gorm:"column:account_level" json:"account_level"`
	Provider          string    `gorm:"column:provider;not null;default:BANK" json:"provider"`
	ProviderType      string    `gorm:"column:provider_type;not null;default:INDIVIDUAL" json:"provider_type"`
	MinPerTransaction float64   `gorm:"column:min_per_transaction;not null" json:"min_per_transaction"`
	MaxPerTransaction float64   `gorm:"column:max_per_transaction;not null" json:"max_per_transaction"`
	MaxPerMonth       float64   `gorm:"column:max_per_month;not null" json:"max_per_month"`
	TransactionType   string    `gorm:"column:transaction_type;not null" json:"transaction_type"`
	Description       string    `gorm:"column:description" json:"description"`
	CurrencySymbol    string    `gorm:"column:currency_symbol" json:"currency_symbol"`
	WalletType        string    `gorm:"column:wallet_type;default:MAIN" json:"wallet_type"`
	Tier              string    `gorm:"column:tier" json:"tier"`
}

// TableName Limit's table name
func (*Limit) TableName() string {
	return TableNameLimit
}
