// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Timestamp int64  `gorm:"column:timestamp;not null" json:"timestamp"`
	Name      string `gorm:"column:name;not null" json:"name"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
