// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayoneerActivitie = "payoneer-activities"

// PayoneerActivitie mapped from table <payoneer-activities>
type PayoneerActivitie struct {
	ActivityID         string    `gorm:"column:ActivityId;primaryKey" json:"ActivityId"`
	Icon               string    `gorm:"column:Icon" json:"Icon"`
	TypeID             int32     `gorm:"column:TypeId" json:"TypeId"`
	Date               time.Time `gorm:"column:Date" json:"Date"`
	Description        string    `gorm:"column:Description" json:"Description"`
	ActivityName       string    `gorm:"column:ActivityName" json:"ActivityName"`
	Amount             string    `gorm:"column:Amount" json:"Amount"`
	Account            string    `gorm:"column:Account" json:"Account"`
	Balance            string    `gorm:"column:Balance" json:"Balance"`
	Status             string    `gorm:"column:Status" json:"Status"`
	SplitAmount        string    `gorm:"column:SplitAmount" json:"SplitAmount"`
	SplitBalance       string    `gorm:"column:SplitBalance" json:"SplitBalance"`
	HasStatement       int32     `gorm:"column:HasStatement" json:"HasStatement"`
	ActivityItemStatus int32     `gorm:"column:ActivityItemStatus" json:"ActivityItemStatus"`
}

// TableName PayoneerActivitie's table name
func (*PayoneerActivitie) TableName() string {
	return TableNamePayoneerActivitie
}
