// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePingPongOrder = "ping-pong-orders"

// PingPongOrder mapped from table <ping-pong-orders>
type PingPongOrder struct {
	OrderID         string `gorm:"column:orderId;primaryKey" json:"orderId"`
	ClientID        string `gorm:"column:clientId" json:"clientId"`
	Amount          string `gorm:"column:amount" json:"amount"`
	Currency        string `gorm:"column:currency" json:"currency"`
	Note            string `gorm:"column:note" json:"note"`
	OrderFinishTime int64  `gorm:"column:orderFinishTime" json:"orderFinishTime"`
}

// TableName PingPongOrder's table name
func (*PingPongOrder) TableName() string {
	return TableNamePingPongOrder
}
