// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvider = "providers"

// Provider mapped from table <providers>
type Provider struct {
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status           int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted        int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	Name             string    `gorm:"column:name" json:"name"`
	Value            string    `gorm:"column:value;primaryKey" json:"value"`
	Group_           string    `gorm:"column:group;not null;default:WEALIFY" json:"group"`
	TransactionTypes string    `gorm:"column:transaction_types;not null" json:"transaction_types"`
	FileID           string    `gorm:"column:file_id" json:"file_id"`
}

// TableName Provider's table name
func (*Provider) TableName() string {
	return TableNameProvider
}
