// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePurpose = "purposes"

// Purpose mapped from table <purposes>
type Purpose struct {
	Name      string    `gorm:"column:name" json:"name"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	IsDeleted int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName Purpose's table name
func (*Purpose) TableName() string {
	return TableNamePurpose
}
