// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRateCustomer = "rate-customer"

// RateCustomer mapped from table <rate-customer>
type RateCustomer struct {
	RateID     string `gorm:"column:rate_id;primaryKey" json:"rate_id"`
	CustomerID int32  `gorm:"column:customer_id;primaryKey" json:"customer_id"`
}

// TableName RateCustomer's table name
func (*RateCustomer) TableName() string {
	return TableNameRateCustomer
}
