// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSocketClient = "socket-clients"

// SocketClient mapped from table <socket-clients>
type SocketClient struct {
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status     int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted  int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	ClientID   string    `gorm:"column:client_id;not null" json:"client_id"`
	Events     string    `gorm:"column:events" json:"events"`
	CustomerID int32     `gorm:"column:customer_id" json:"customer_id"`
	EmployeeID int32     `gorm:"column:employee_id" json:"employee_id"`
	Params     string    `gorm:"column:params" json:"params"`
}

// TableName SocketClient's table name
func (*SocketClient) TableName() string {
	return TableNameSocketClient
}
