// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemPaymentPriority = "system-payment-priority"

// SystemPaymentPriority mapped from table <system-payment-priority>
type SystemPaymentPriority struct {
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
	Status    int32     `gorm:"column:status;not null;default:1" json:"status"`
	IsDeleted int32     `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Orders    string    `gorm:"column:orders;not null" json:"orders"`
	Provider  string    `gorm:"column:provider;not null;default:BANK" json:"provider"`
}

// TableName SystemPaymentPriority's table name
func (*SystemPaymentPriority) TableName() string {
	return TableNameSystemPaymentPriority
}
