// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTazapayActivitie = "tazapay-activities"

// TazapayActivitie mapped from table <tazapay-activities>
type TazapayActivitie struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	Amount         float32   `gorm:"column:amount;not null" json:"amount"`
	CurrencySymbol string    `gorm:"column:currency_symbol;not null" json:"currency_symbol"`
	Provider       string    `gorm:"column:provider;not null;default:MERCURY" json:"provider"`
	TransactionID  string    `gorm:"column:transaction_id" json:"transaction_id"`
	Reference      string    `gorm:"column:reference;not null" json:"reference"`
	Detail         string    `gorm:"column:detail" json:"detail"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
}

// TableName TazapayActivitie's table name
func (*TazapayActivitie) TableName() string {
	return TableNameTazapayActivitie
}
