// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTransferMethodField = "transfer-method-field"

// TransferMethodField mapped from table <transfer-method-field>
type TransferMethodField struct {
	TransferMethodID string `gorm:"column:transfer_method_id;primaryKey" json:"transfer_method_id"`
	FieldID          string `gorm:"column:field_id;primaryKey" json:"field_id"`
}

// TableName TransferMethodField's table name
func (*TransferMethodField) TableName() string {
	return TableNameTransferMethodField
}
