// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVirtualAccountPurpose = "virtual-account-purposes"

// VirtualAccountPurpose mapped from table <virtual-account-purposes>
type VirtualAccountPurpose struct {
	VirtualAccountID int32 `gorm:"column:virtual_account_id;primaryKey" json:"virtual_account_id"`
	PurposeID        int32 `gorm:"column:purpose_id;primaryKey" json:"purpose_id"`
}

// TableName VirtualAccountPurpose's table name
func (*VirtualAccountPurpose) TableName() string {
	return TableNameVirtualAccountPurpose
}
