// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWiseActivitie = "wise-activities"

// WiseActivitie mapped from table <wise-activities>
type WiseActivitie struct {
	ID              string `gorm:"column:id;primaryKey" json:"id"`
	Type            string `gorm:"column:type" json:"type"`
	Resource        string `gorm:"column:resource" json:"resource"`
	Title           string `gorm:"column:title" json:"title"`
	Description     string `gorm:"column:description" json:"description"`
	PrimaryAmount   string `gorm:"column:primaryAmount" json:"primaryAmount"`
	SecondaryAmount string `gorm:"column:secondaryAmount" json:"secondaryAmount"`
	Status          string `gorm:"column:status" json:"status"`
	CreatedOn       string `gorm:"column:createdOn" json:"createdOn"`
	UpdatedOn       string `gorm:"column:updatedOn" json:"updatedOn"`
}

// TableName WiseActivitie's table name
func (*WiseActivitie) TableName() string {
	return TableNameWiseActivitie
}
