package constants

// Payment Status
const (
	PAYMENT_STATUS_PENDING  = "PENDING"
	PAYMENT_STATUS_PROCESS  = "PROCESS"
	PAYMENT_STATUS_APPROVED = "APPROVED"
	PAYMENT_STATUS_REJECTED = "REJECTED"
)

// Setting Keys
const (
	SETTING_KEY_VA_LIMIT                    = "VA_LIMIT"
	SETTING_KEY_VA_FEE                      = "VA_FEE"
	SETTING_KEY_LARK_CHAT_ID                = "LARK_CHAT_ID"
	SETTING_KEY_INACTIVE_VA_RESTRICTED_HOUR = "INACTIVE_VA_RESTRICTED_HOUR"
	SETTING_KEY_YOOBIL_AUTO_WITHDRAW        = "YOOBIL_AUTO_WITHDRAW"
	SETTING_KEY_YOOBIL_MAP_BANK             = "YOOBIL_MAP_BANK"
	SETTING_KEY_NEOX_AUTO_WITHDRAW          = "NEOX_AUTO_WITHDRAW"
	SETTING_KEY_NEOX_MAP_BANK               = "NEOX_MAP_BANK"
	SETTING_KEY_VC_FEE                      = "VC_FEE"
)

// Order
const (
	ORDER_DESC = "DESC"
	ORDER_ASC  = "ASC"
)

// Verification Status
const (
	VERIFICATION_STATUS_UNVERIFIED = "UNVERIFIED"
	VERIFICATION_STATUS_VERIFIED   = "VERIFIED"
)

// Two Factor Method
const (
	TWO_FACTOR_METHOD_EMAIL             = "EMAIL"
	TWO_FACTOR_METHOD_AUTHENTICATOR_APP = "AUTHENTICATOR_APP"
	TWO_FACTOR_METHOD_SMS               = "SMS"
)

// Two Factor Status
const (
	TWO_FACTOR_STATUS_ENABLE  = "ENABLE"
	TWO_FACTOR_STATUS_DISABLE = "DISABLE"
)

// Notification Group
const (
	NOTIFICATION_GROUP_SYSTEM    = "SYSTEM"
	NOTIFICATION_GROUP_IMPORTANT = "IMPORTANT"
)

// Notification Types
const (
	NOTIFICATION_TYPE_WELCOME                        = "WELCOME"
	NOTIFICATION_TYPE_NEW_DEVICE_LOGIN               = "NEW_DEVICE_LOGIN"
	NOTIFICATION_TYPE_UPDATE_ACCOUNT_LEVEL           = "UPDATE_ACCOUNT_LEVEL"
	NOTIFICATION_TYPE_UPDATE_ACCOUNT_TYPE            = "UPDATE_ACCOUNT_TYPE"
	NOTIFICATION_TYPE_UPGRADE_TIER                   = "UPGRADE_TIER"
	NOTIFICATION_TYPE_DOWNGRADE_TIER                 = "DOWNGRADE_TIER"
	NOTIFICATION_TYPE_ENABLE_WEALIFY_WALLET_FEATURE  = "ENABLE_WEALIFY_WALLET_FEATURE"
	NOTIFICATION_TYPE_DISABLE_WEALIFY_WALLET_FEATURE = "DISABLE_WEALIFY_WALLET_FEATURE"
	NOTIFICATION_TYPE_ADJUST_BALANCE                 = "ADJUST_BALANCE"
	NOTIFICATION_TYPE_REJECT_KYC                     = "REJECT_KYC"
	NOTIFICATION_TYPE_APPROVE_KYC                    = "APPROVE_KYC"
	NOTIFICATION_TYPE_REJECT_KYB                     = "REJECT_KYB"
	NOTIFICATION_TYPE_APPROVE_KYB                    = "APPROVE_KYB"
	NOTIFICATION_TYPE_APPROVE_PAYMENT                = "APPROVE_PAYMENT"
	NOTIFICATION_TYPE_REJECT_PAYMENT                 = "REJECT_PAYMENT"
	NotificationTypeCreateVirtualAccount             = "CREATE_VIRTUAL_ACCOUNT"
	NotificationTypeApproveWithdraw                  = "APPROVE_WITHDRAW"
	NotificationTypeRejectWithdraw                   = "REJECT_WITHDRAW"
	NotificationTypeApproveTopUp                     = "APPROVE_TOP_UP"
)

// File Driver
const (
	FILE_DRIVER_LARK   = "LARK"
	FILE_DRIVER_GOOGLE = "GOOGLE"
	FILE_DRIVER_AWS    = "AWS"
)

// Session Type
const (
	SESSION_TYPE_CUSTOMER = "CUSTOMER"
	SESSION_TYPE_EMPLOYEE = "EMPLOYEE"
)

// Payment Type
const (
	PAYMENT_TYPE_BANK     = "BANK"
	PAYMENT_TYPE_E_WALLET = "E_WALLET"
)

// KY Verification Status
const (
	KY_VERIFICATION_STATUS_PENDING  = "PENDING"
	KY_VERIFICATION_STATUS_APPROVED = "APPROVED"
	KY_VERIFICATION_STATUS_REJECTED = "REJECTED"
)

// KY Request Status
const (
	KY_REQUEST_STATUS_PENDING   = "PENDING"
	KY_REQUEST_STATUS_COMPLETED = "COMPLETED"
)

// Identification Type
const (
	IDENTIFICATION_TYPE_PASSPORT       = "PASSPORT"
	IDENTIFICATION_TYPE_IDENTITY_CARD  = "IDENTITY_CARD"
	IDENTIFICATION_TYPE_DRIVER_LICENSE = "DRIVER_LICENSE"
)

// Document Type
const (
	DOCUMENT_TYPE_BANK_STATEMENT         = "BANK_STATEMENT"
	DOCUMENT_TYPE_INTERNET_SERVICE_BILLS = "INTERNET_SERVICE_BILLS"
	DOCUMENT_TYPE_CREDIT_NOTE            = "CREDIT_NOTE"
	DOCUMENT_TYPE_TAX_STATEMENT          = "TAX_STATEMENT"
	DOCUMENT_TYPE_BANK_REFERENCE_LETTER  = "BANK_REFERENCE_LETTER"
)

// Request Type
const (
	REQUEST_TYPE_TOP_UP      = "TOP_UP"
	REQUEST_TYPE_WITHDRAWAL  = "WITHDRAWAL"
	REQUEST_TYPE_PROFILE     = "PROFILE"
	REQUEST_TYPE_PAYMENT     = "PAYMENT"
	REQUEST_TYPE_KYC_LEVEL_1 = "KYC_LEVEL_1"
	REQUEST_TYPE_KYC_LEVEL_2 = "KYC_LEVEL_2"
	REQUEST_TYPE_KYC_LEVEL_3 = "KYC_LEVEL_3"
	REQUEST_TYPE_KYB_LEVEL_1 = "KYB_LEVEL_1"
	REQUEST_TYPE_KYB_LEVEL_2 = "KYB_LEVEL_2"
	REQUEST_TYPE_KYB_LEVEL_3 = "KYB_LEVEL_3"
)

// Field Type
const (
	FIELD_TYPE_MEDIA        = "MEDIA"
	FIELD_TYPE_DOCUMENT     = "DOCUMENT"
	FIELD_TYPE_COUNTRY      = "COUNTRY"
	FIELD_TYPE_PHONE_NUMBER = "PHONE_NUMBER"
	FIELD_TYPE_CALLING_CODE = "CALLING_CODE"
	FIELD_TYPE_EMAIL        = "EMAIL"
	FIELD_TYPE_TEXT         = "TEXT"
	FIELD_TYPE_NUMBER       = "NUMBER"
	FIELD_TYPE_NUMERIC      = "NUMERIC"
	FIELD_TYPE_DATE         = "DATE"
	FIELD_TYPE_BOOLEAN      = "BOOLEAN"
)

// Request Status
const (
	REQUEST_STATUS_PENDING   = "PENDING"
	REQUEST_STATUS_CANCELLED = "CANCELLED"
	REQUEST_STATUS_RESPONDED = "RESPONDED"
)

// Wallet Type
const (
	WALLET_TYPE_MAIN = "MAIN"
	WALLET_TYPE_VA   = "VA"
	WALLET_TYPE_VC   = "VC"
)

// Wallet Currency
const (
	WALLET_CURRENCY_VNDW = "VNDW"
	WALLET_CURRENCY_VNDY = "VNDY"
	WALLET_CURRENCY_USD  = "USD"
)

// Transaction Type
const (
	TRANSACTION_TYPE_TOP_UP     = "TOP_UP"
	TRANSACTION_TYPE_WITHDRAWAL = "WITHDRAWAL"
	TRANSACTION_TYPE_INTERNAL   = "INTERNAL"
)

// Transaction VC Type
const (
	TRANSACTION_VC_TYPE_TOP_UP     = "TOP_UP"
	TRANSACTION_VC_TYPE_WITHDRAWAL = "WITHDRAWAL"
	TRANSACTION_VC_TYPE_PAYMENT    = "PAYMENT"
)

// VC Detail Transaction Type
const (
	VC_DETAIL_TRANSACTION_TYPE_CARD_TOP_UP           = "CARD_TOP_UP"
	VC_DETAIL_TRANSACTION_TYPE_CARD_ISSUE_TOP_UP     = "CARD_ISSUE_TOP_UP"
	VC_DETAIL_TRANSACTION_TYPE_CARD_WITHDRAW         = "CARD_WITHDRAW"
	VC_DETAIL_TRANSACTION_TYPE_CARD_PAYMENT          = "CARD_PAYMENT"
	VC_DETAIL_TRANSACTION_TYPE_WALLET_TOP_UP         = "WALLET_TOP_UP"
	VC_DETAIL_TRANSACTION_TYPE_WALLET_WITHDRAW       = "WALLET_WITHDRAW"
	VC_DETAIL_TRANSACTION_TYPE_WALLET_ISSUE_WITHDRAW = "WALLET_ISSUE_WITHDRAW"
	VC_DETAIL_TRANSACTION_TYPE_WALLET_REFUND         = "WALLET_REFUND"
)

// Platform Status
const (
	PLATFORM_STATUS_ACTIVE   = "ACTIVE"
	PLATFORM_STATUS_INACTIVE = "INACTIVE"
)

// Platform Type
const (
	PLATFORM_TYPE_DEFAULT = "DEFAULT"
	PLATFORM_TYPE_CUSTOM  = "CUSTOM"
)

// Tier
const (
	TIER_STANDARD = "STANDARD"
	TIER_SILVER   = "SILVER"
	TIER_GOLD     = "GOLD"
	TIER_DIAMOND  = "DIAMOND"
)

// Transaction Status
const (
	TRANSACTION_STATUS_PENDING   = "PENDING"
	TRANSACTION_STATUS_PROCESS   = "PROCESS"
	TRANSACTION_STATUS_APPROVED  = "APPROVED"
	TRANSACTION_STATUS_REJECTED  = "REJECTED"
	TRANSACTION_STATUS_WAITING   = "WAITING"
	TRANSACTION_STATUS_CANCELLED = "CANCELLED"
)

// Transaction VC Status
const (
	TRANSACTION_VC_STATUS_PROCESSING = "PROCESSING"
	TRANSACTION_VC_STATUS_SUCCESS    = "SUCCESS"
	TRANSACTION_VC_STATUS_FAILURE    = "FAILURE"
)

// VA Bank
const (
	VA_BANK_BIDV = "BIDV"
	VA_BANK_KLB  = "KLB"
	VA_BANK_MSB  = "MSB"
	VA_BANK_TCB  = "TCB"
)

// Third Party Status
const (
	THIRD_PARTY_STATUS_CORRECT   = "CORRECT"
	THIRD_PARTY_STATUS_INCORRECT = "INCORRECT"
)

// Transaction History Type
const (
	TRANSACTION_HISTORY_TYPE_CREATED       = "CREATED"
	TRANSACTION_HISTORY_TYPE_UPDATED       = "UPDATED"
	TRANSACTION_HISTORY_TYPE_REVIEWED      = "REVIEWED"
	TRANSACTION_HISTORY_TYPE_RESOLVED      = "RESOLVED"
	TRANSACTION_HISTORY_TYPE_CHANGE_STATUS = "CHANGE_STATUS"
)

// Rate Amount Type
const (
	RATE_VALUE_TYPE_MANUAL = "MANUAL"
	RATE_VALUE_TYPE_LINKED = "LINKED"
)

// Fee Amount Type
const (
	FEE_VALUE_TYPE_PERCENT = "PERCENT"
	FEE_VALUE_TYPE_FIXED   = "FIXED"
)

// Account Level
const (
	ACCOUNT_LEVEL_1   = 1
	ACCOUNT_LEVEL_2   = 2
	ACCOUNT_LEVEL_3   = 3
	ACCOUNT_LEVEL_VIP = 4
)

// Account Type
const (
	ACCOUNT_TYPE_BUSINESS   = "BUSINESS"
	ACCOUNT_TYPE_INDIVIDUAL = "INDIVIDUAL"
)

// Customer Type
const (
	CUSTOMER_TYPE_NORMAL = "NORMAL"
	CUSTOMER_TYPE_SALE   = "SALE"
)

// Provider
const (
	PROVIDER_BANK        = "BANK"
	PROVIDER_WEALIFY     = "WEALIFY"
	PROVIDER_PING_PONG   = "PING_PONG"
	PROVIDER_LIAN_LIAN   = "LIAN_LIAN"
	PROVIDER_PAYONEER    = "PAYONEER"
	PROVIDER_WORLD_FIRST = "WORLD_FIRST"
	PROVIDER_TAZAPAY     = "TAZAPAY"
	PROVIDER_MERCURY     = "MERCURY"
	PROVIDER_YOOBIL      = "YOOBIL"
	PROVIDER_NEOX        = "NEOX"
	PROVIDER_G_TEL       = "G_TEL"
)

// Provider Group
const (
	PROVIDER_GROUP_BANK     = "BANK"
	PROVIDER_GROUP_E_WALLET = "E_WALLET"
	PROVIDER_GROUP_WEALIFY  = "WEALIFY"
	PROVIDER_GROUP_VA       = "VA"
)

// Provider Type
const (
	PROVIDER_TYPE_BUSINESS   = "BUSINESS"
	PROVIDER_TYPE_INDIVIDUAL = "INDIVIDUAL"
)

// Socket Event
const (
	SOCKET_EVENT_NOTIFICATIONS                        = "notifications"
	SOCKET_EVENT_NEW_NOTIFICATION                     = "notifications/new"
	SOCKET_EVENT_CMS_NOTIFICATIONS                    = "cms/notifications"
	SOCKET_EVENT_CMS_NEW_NOTIFICATIONS                = "cms/notifications/new"
	SOCKET_EVENT_MAIN_WALLETS                         = "main-wallets"
	SOCKET_EVENT_CAMPAIGN_REFERRAL_ALL_TIME_UPDATE    = "campaign/referral/all-time:update"
	SOCKET_EVENT_CAMPAIGN_REFERRAL_CURRENT_UPDATE     = "campaign/referral/current:update"
	SOCKET_EVENT_CAMPAIGN_TRANSACTION_ALL_TIME_UPDATE = "campaign/transactions/all-time:update"
	SOCKET_EVENT_CAMPAIGN_TRANSACTION_CURRENT_UPDATE  = "campaign/transactions/current:update"
)

// VA Status
const (
	VA_STATUS_ACTIVE     = "ACTIVE"
	VA_STATUS_INACTIVE   = "INACTIVE"
	VA_STATUS_RESTRICTED = "RESTRICTED"
	VA_STATUS_PENDING    = "PENDING"
	VA_STATUS_PROCESS    = "PROCESS"
	VA_STATUS_REJECTED   = "REJECTED"
)

// Boolean String
const (
	BOOLEAN_STRING_TRUE  = "true"
	BOOLEAN_STRING_FALSE = "false"
)

// DateTime Format
const (
	DATE_TIME_FORMAT_HHMMDDMMYYYY  = "15:04 02/01/2006"
	DATE_TIME_FORMAT_DDMMYYYY      = "02/01/2006"
	DATE_TIME_FORMAT_DDMMYYYY_DASH = "02-01-2006"
	DATE_TIME_FORMAT_DDMMYYYYHHMMA = "02/01/2006 03:04 PM"
)

// System Constants
const (
	SYSTEM_UNIT          = "VNDW"
	USD_CODE             = "USD"
	VND_CODE             = "VND"
	VN_ISO_CODE2         = "VN"
	FORMAT_DATE          = "2006-01-02 15:04:05"
	MAXIMUM_NUMBER       = 999999999999999
	REFERRAL_CODE_LENGTH = 10
)

// Response structures
type ConstantInfo struct {
	Name  string      `json:"name"`
	Value interface{} `json:"value"`
	Icon  string      `json:"icon,omitempty"`
}

type ProviderInfo struct {
	Name             string   `json:"name"`
	Value            string   `json:"value"`
	Icon             string   `json:"icon,omitempty"`
	Group            string   `json:"group"`
	TransactionTypes []string `json:"transaction_types"`
}

// Constants data
var Constants = map[string]interface{}{
	"payment_status": map[string]ConstantInfo{
		PAYMENT_STATUS_PENDING:  {Name: "Pending", Value: PAYMENT_STATUS_PENDING},
		PAYMENT_STATUS_PROCESS:  {Name: "Process", Value: PAYMENT_STATUS_PROCESS},
		PAYMENT_STATUS_APPROVED: {Name: "Approved", Value: PAYMENT_STATUS_APPROVED},
		PAYMENT_STATUS_REJECTED: {Name: "Rejected", Value: PAYMENT_STATUS_REJECTED},
	},
	"order": map[string]ConstantInfo{
		ORDER_ASC:  {Name: "Earliest", Value: ORDER_ASC},
		ORDER_DESC: {Name: "Oldest", Value: ORDER_DESC},
	},
	"verification_status": map[string]ConstantInfo{
		VERIFICATION_STATUS_UNVERIFIED: {Name: "Unverified", Value: VERIFICATION_STATUS_UNVERIFIED},
		VERIFICATION_STATUS_VERIFIED:   {Name: "Verified", Value: VERIFICATION_STATUS_VERIFIED},
	},
	"two_factor_method": map[string]ConstantInfo{
		TWO_FACTOR_METHOD_EMAIL:             {Name: "Email", Value: TWO_FACTOR_METHOD_EMAIL},
		TWO_FACTOR_METHOD_AUTHENTICATOR_APP: {Name: "Authenticator app", Value: TWO_FACTOR_METHOD_AUTHENTICATOR_APP},
		TWO_FACTOR_METHOD_SMS:               {Name: "SMS", Value: TWO_FACTOR_METHOD_SMS},
	},
	"two_factor_status": map[string]ConstantInfo{
		TWO_FACTOR_STATUS_ENABLE:  {Name: "Enable", Value: TWO_FACTOR_STATUS_ENABLE},
		TWO_FACTOR_STATUS_DISABLE: {Name: "Disable", Value: TWO_FACTOR_STATUS_DISABLE},
	},
	"notification_group": map[string]ConstantInfo{
		NOTIFICATION_GROUP_IMPORTANT: {Name: "Important", Value: NOTIFICATION_GROUP_IMPORTANT},
		NOTIFICATION_GROUP_SYSTEM:    {Name: "System", Value: NOTIFICATION_GROUP_SYSTEM},
	},
	"account_level": map[string]ConstantInfo{
		"1": {Name: "Level 1", Value: ACCOUNT_LEVEL_1},
		"2": {Name: "Level 2", Value: ACCOUNT_LEVEL_2},
		"3": {Name: "Level 3", Value: ACCOUNT_LEVEL_3},
		"4": {Name: "VIP", Value: ACCOUNT_LEVEL_VIP},
	},
	"account_type": map[string]ConstantInfo{
		ACCOUNT_TYPE_BUSINESS:   {Name: "Business", Value: ACCOUNT_TYPE_BUSINESS},
		ACCOUNT_TYPE_INDIVIDUAL: {Name: "Individual", Value: ACCOUNT_TYPE_INDIVIDUAL},
	},
	"provider": map[string]ProviderInfo{
		PROVIDER_BANK:        {Name: "Bank", Value: PROVIDER_BANK, Group: PROVIDER_GROUP_BANK, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_WEALIFY:     {Name: "Wealify", Value: PROVIDER_WEALIFY, Group: PROVIDER_GROUP_WEALIFY, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL, TRANSACTION_TYPE_INTERNAL}},
		PROVIDER_PING_PONG:   {Name: "Ping Pong", Value: PROVIDER_PING_PONG, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_LIAN_LIAN:   {Name: "Lian Lian", Value: PROVIDER_LIAN_LIAN, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_PAYONEER:    {Name: "Payoneer", Value: PROVIDER_PAYONEER, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_WORLD_FIRST: {Name: "World First", Value: PROVIDER_WORLD_FIRST, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_TAZAPAY:     {Name: "Tazapay", Value: PROVIDER_TAZAPAY, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_MERCURY:     {Name: "Mercury", Value: PROVIDER_MERCURY, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_YOOBIL:      {Name: "Yoobil", Value: PROVIDER_YOOBIL, Group: PROVIDER_GROUP_VA, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_NEOX:        {Name: "Neox", Value: PROVIDER_NEOX, Group: PROVIDER_GROUP_VA, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
		PROVIDER_G_TEL:       {Name: "G Tel", Value: PROVIDER_G_TEL, Group: PROVIDER_GROUP_E_WALLET, TransactionTypes: []string{TRANSACTION_TYPE_TOP_UP, TRANSACTION_TYPE_WITHDRAWAL}},
	},
	"provider_type": map[string]ConstantInfo{
		PROVIDER_TYPE_BUSINESS:   {Name: "Business", Value: PROVIDER_TYPE_BUSINESS},
		PROVIDER_TYPE_INDIVIDUAL: {Name: "Individual", Value: PROVIDER_TYPE_INDIVIDUAL},
	},
}
